version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goal_tracker_backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=goaltracker
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRATION=1h
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - goaltracker_network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: goal_tracker_postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=goaltracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - goaltracker_network
    restart: unless-stopped

networks:
  goaltracker_network:
    driver: bridge

volumes:
  postgres_data:
